export const RACES_FETCHING = 'RACES_FETCHING';
export const ADD_RACES = 'ADD_RACES';
export const RACES_SET_ERRORS = 'RACES_SET_ERRORS';
export const RACES_SET_LIMIT = 'RACES_SET_LIMIT';
export const RACES_SET_OFFSET = 'RACES_SET_OFFSET';
export const RACES_SET_TOTAL = 'RACES_SET_TOTAL';
export const RACES_SET_CURRENT_PAGE = 'RACES_SET_CURRENT_PAGE';
export const RACES_RESET = 'RACES_RESET';

